<?php
// connect, set vars, and increase temp memory limit so the code generator can run
session_start();
ini_set("memory_limit","16M");
// if appropriate session variables arent set, send the user back to the home page
if(!isset($_SESSION['userID'])){
    header("Location:../index.php");
    die();
  }

// connect to server
$servername = "165.227.46.101";
$username= "user1";
$password = "access";
$dbname = "loginDB";

//$conn = new mysqli($servername,$username,$password,$dbname);
try{
  $conn = new PDO("mysql:host=localhost;dbname=$dbname",$username,$password);
  } catch (PDOException $e){
      die("Failed to connect to database: ". $e->getMessage());
  }

// generate code using the $x possible characters, length 5
function generateCode($length=5){
 return substr(str_shuffle(str_repeat($x='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ',ceil($length/strlen($x)) )),1,$length);
}

// get the classroomname from the create classroom form, create an autogenerated code, and insert it into the database, the current userID is the admin
$className = $_POST['classroomName'];
$code  = "".generateCode()."";
$tmp = $_SESSION['userID'];

$sql="INSERT INTO classrooms (classCode, adminID, className) VALUES ('$code','$tmp','$className')";


// if the code generated already exists, it will keep making new ones until its not new
//$result=mysqli_query($conn,$sql);
$result=$conn->query($sql);
while(!$result){
    $code=generateCode();
    $tmp = $_SESSION['userID'];
    $sql="INSERT INTO classrooms (classCode, adminID, className) VALUES ('$code','$tmp','$className')";
}

$classID_query = "SELECT classID FROM classrooms
WHERE classCode='".$code."'";
//$classID = mysqli_fetch_assoc(mysqli_query($conn,$classID_query));
$step = $conn->query($classID_query);
$classID= $step->fetch(PDO::FETCH_ASSOC);

// make the creator of the class enrolled
$tmp2 = $classID["classID"];
$enroll = "INSERT INTO enrolled (classID, studentID) VALUES ('$tmp2','$tmp')";

//$result2=mysqli_query($conn,$enroll);
$result2=$conn->query($enroll);


//$conn->close();
$conn=null;
header("Location:../class/dashboard.php");
die();

?>
